name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get --quiet update
          sudo apt-get --quiet install python3-pkg-resources python3-pip ninja-build libcurl4-openssl-dev libssl-dev libpulse-dev
          sudo apt purge cmake
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt-get --quiet update --yes && sudo -E apt-get --quiet install --yes cmake

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'

      - name: Build RTME c++/golang
        run: |
          bash setup/internal/linux.sh 
